version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.35
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          name: "Build Production w/ Hugo"
          command: HUGO_ENV=production hugo -v -s src/
      - run:
          name: "Build Staging w/ Hugo"
          command: HUGO_ENV=staging hugo --config=src/config.toml,src/config-staging.toml -v -s src/ -d staging-files/
      - run:
          name: "Test Website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --url-ignore "/NightOfAcrylics.com/"
      - add_ssh_keys
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'web01.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJiGRY6N9WYQ0vy6cTiwAgNbc6ueJmVo/EafBtmT7bcD6cQMbipYM/KfYQ2lCn2TxqWepZKYoyoVQXgArycCOns=' >> ~/.ssh/known_hosts
              rsync -va --delete src/public/ staticweb@web01.revidian.net:www/nightofacrylics.com/public_html
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              echo 'web01.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJiGRY6N9WYQ0vy6cTiwAgNbc6ueJmVo/EafBtmT7bcD6cQMbipYM/KfYQ2lCn2TxqWepZKYoyoVQXgArycCOns=' >> ~/.ssh/known_hosts
              rsync -va --delete src/staging-files/ staticweb@web01.revidian.net:www/nightofacrylics.com/staging
            fi
