baseURL = "https://NightOfAcrylics.com"
languageCode = "en-us"
title = "Night of Acrylics"

theme = "noa-2017"
googleAnalytics = "UA-108010770-1"

enableEmoji = true
canonifyurls = true
paginate = 3

[params]
description = "Night Of Acrylics is injecting a booster shot of fun into your paint party experience. Join us at your local restaurant or bar for painting, music, food and drinks."
tagline = "Have fun, Paint fun."
mailchimpURL = "//NightOfAcrylics.us16.list-manage.com/subscribe/post?u=146e75a1066df1e45e94aa5be&amp;id=2746dc535d"
facebook   = "https://facebook.com/NightOfAcrylics"
twitter    = "https://twitter.com/NightOfAcrylics"
instagram  = "https://instagram.com/NightOfAcrylics"

[Social]
	twitter = "NightOfAcrylics"

[blackfriday]
	hrefTargetBlank	=	true

[outputs]
page = ["HTML", "poster", "ig"]

[outputFormats]
[outputFormats.poster]
name       = "poster"
mediaType  = "text/html"
baseName   = "poster"
isHTML     = true
[outputFormats.ig]
name       = "ig"
mediaType  = "text/html"
baseName   = "ig"
isHTML     = true


[[menu.main]]
	name	= "Home"
	url		= "/"
	weight	= -1

[[menu.main]]
	name	= "Events"
	url		= "/events"
	weight	= 5

[[menu.main]]
	name	= "Newsletter"
	url		= "/newsletter"
	weight	= 10
