baseURL = "http://NightOfAcrylics.com"
languageCode = "en-us"
title = "Night of Acrylics"

theme = "hugo-theme-lean-launch-page"
googleAnalytics = "UA-108010770-1"

enableEmoji = true
canonifyurls = true
paginate = 3

[params]
description = ""
tagline = "Have fun, Paint fun."
mailchimpURL = "//NightOfAcrylics.us16.list-manage.com/subscribe/post?u=146e75a1066df1e45e94aa5be&amp;id=2746dc535d"
facebook   = "https://facebook.com/NightOfAcrylics"
twitter    = "https://twitter.com/NightOfAcrylics"
instagram  = "https://instagram.com/NightOfAcrylics"

[blackfriday]
	hrefTargetBlank	=	true

[[menu.main]]
	name	= "Home"
	url		= "/"
	weight	= -1
